### ISSUE TITLE
Recommend quoting of type in `typing.cast()`

### ISSUE THREAD

**Issue by ngnpope** [snok/flake8-type-checking#114]
See https://twitter.com/zzzeek/status/1483093707637366795

For particularly complex casts there can be a significant performance hit, particularly in hot code paths, e.g.

```python
In [1]: %timeit list[tuple[bool | float | int | str, ...]] | None
451 ns ± 18.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [2]: %timeit "list[tuple[bool | float | int | str, ...]] | None"
4.01 ns ± 0.0235 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)
```

Given that the type in the cast is purely for type checkers there is probably no good reason why it shouldn't always be quoted.

**Comment by ngnpope** [comment]
I don't think so as `typing.cast()` is just a normal function call, so always at runtime.

It just so happens that it does nothing with that typing info at runtime. (See [here](https://github.com/python/cpython/blob/7c185017a9b68c851ea079ef31f6bcef694378ac/Lib/typing.py#L2216-L2224).)

As far as `mypy` is concerned, I tested all combinations of quoting or no quoting and the annotations import present or not, and it behaves the same in all cases.

On that basis this wouldn't belong to the `TC1` or `TC2` error ranges, but perhaps just as a `TC006` error code.

**Comment by sondrelg** [comment]
Yeah sounds good, and sound relevant to this plugin, so I'd be happy to add this. Would you be interested in creating a PR?

**Comment by JonasKs** [comment]
Wow - I'm shook by those numbers! Would be awesome to have that process covered by this plugin indeed.

**Comment by ngnpope** [comment]
> Would you be interested in creating a PR?

Sure. Might be next week before I get around to it. 🙂
