### ISSUE TITLE
Codes conflict with tryceraptops

### ISSUE THREAD

**Issue by Aplietexe** [snok/flake8-type-checking#147]
Both `flake8-type-checking` and `tryceraptops` are using the same `TC` prefix in the same range, which makes it impossible to use both plugins at the same time. 
[tryceraptops violations doc](https://github.com/guilatrova/tryceratops/tree/main/docs/violations)

**Comment by sondrelg** [comment]
I'm not keen on changing the error codes to be honest. Perhaps this could be solved upstream, if flake8 devs accepted a feature proposal for error code aliasing? 

Just did a 5 minute scan of flake8 issues and can't see that it has been raised before (though, please double check). [This post](https://github.com/PyCQA/flake8/issues/590#issue-849584140) also seems to contain some motivating examples for such a feature. Colliding error codes will most likely pop up more and more as the ecosystem grows.

If you have other suggestions, I'm also happy to hear them 🙂

**Comment by Aplietexe** [comment]
I don't think there's another way, at least until aliasing is implemented. Thanks anyway.

**Comment by seapagan** [comment]
Just a quick note to say that Triceratops have [changed their prefix to `TRY`](https://github.com/guilatrova/tryceratops/pull/55) a couple of months ago, so both should now be usable together.

**Comment by sondrelg** [comment]
Great! Thanks @seapagan 👏
