### ISSUE TITLE
False-Positive on TC002, when `if TYPE_CHECKING is True:` statement is used.

### ISSUE THREAD

**Issue by iamibi** [snok/flake8-type-checking#156]
When using a more explicit statement `if TYPE_CHECKING is True:`, the plugin reports `TC002` which is incorrect. 
The type checking explicit value to True is a good secure coding practice, specially with a dynamically typed language such as Python.

**Comment by sondrelg** [comment]
Thanks for reporting this @iamibi, I definitely understand your motivation. To be honest, I don't think adding the `is True` adds any value here, but I would be happy to accept contribution which amends the code to add this pattern. 

Just so you know, every pattern like this has to be mapped more or less explicitly, so there will always be a need to draw a line in the sand somewhere, in terms of how complex the plugin should be. It isn't a bug, we just haven't added this extra handling yet :+1:

**Comment by sondrelg** [comment]
Let me know if you have questions, I'd be happy to help :relaxed:
