### ISSUE TITLE
AttributeError from checker.py

### ISSUE THREAD

**Issue by Yobmod** [snok/flake8-type-checking#34]
Hi,

I just freshly installed this and flake8 on python3.7 and on any use I'm getting an error on simple `flake8 file.py` . Last call of the traceback is:

`  File "c:\python37\lib\site-packages\flake8_type_checking\checker.py", line 325, in visit_FunctionDef
    for i in range(node.lineno, node.end_lineno + 1):  # type: ignore
AttributeError: 'FunctionDef' object has no attribute 'end_lineno'`

bug-report info:
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.7.3",
    "system": "Windows"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-type-checking",
      "version": "1.0.3"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.7.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.3.1"
    }
  ],
  "version": "3.9.2"
}

**Comment by sondrelg** [comment]
Hi @Yobmod, thanks for submitting the issue! 

It looks like `end_lineno` was implemented in Python 3.8 (see [here](https://restrictedpython.readthedocs.io/en/latest/contributing/changes_from37to38.html)) 🤔 

Since mapping the start and end of different ast objects is pretty integral to how the plugin functions I'm not sure we'd be able to create a workaround for python versions <= 3.8, but you're definitely free to try to if you want. 

If not, I guess I should probably change the package metadata to only support Python 3.8+ 🙂 Sorry about that

**Comment by Yobmod** [comment]
Ah, ok. Thanks for the fast reply.
I seem to spend all my time dealing with typing changes between versions, lol.

**Comment by sondrelg** [comment]
Updated python versions in https://github.com/snok/flake8-type-checking/commit/ae69260264bd024a762d1b2adbfb809ddacf2b1e 🙂

**Comment by kveretennicov** [comment]
:wave: Guys, please consider releasing metadata fix to PyPI, it's still advertised as 3.7-compatible there and people run into this issue.

By the way, isn't [this note from ast docs](https://docs.python.org/3.9/library/ast.html#ast.AST.end_lineno) a little worrying?

> Note that the end positions are not required by the compiler and are therefore optional.

It implies you are relying on something that does not necessarily exist, even in 3.8+. This is confirmed by [ast's typeshed typings](https://github.com/python/typeshed/blob/ce11072dbeda014a1702f929770628f247f5eabc/stubs/typed-ast/typed_ast/ast3.pyi) - `end_lineno` is nowhere to be seen.

**Comment by sondrelg** [comment]
Good point. I'll update the metadata tonight after fixing broken tests in v3.8 👍 

Regarding the optionality of `end_lineno` - I've not personally seen any problems on Python 3.8+, and we've not had any issues as far as I can remember, so I think I'll assume it's fine until proven otherwise 🙂 Happy to be convinced otherwise though.

**Comment by sondrelg** [comment]
Metadata has been updated in v1.0.4 🙂 

![image](https://user-images.githubusercontent.com/25310870/139597027-b6ccb3ea-f813-4344-9901-60a550428b65.png)

**Comment by vect-tmazzucotelli** [comment]
In case you'd like to support Python 3.7 again (at least until mid-2023 when it reaches EOL), here's a solution (roughly stripped down) I've been using in a project of mine:

```python
import inspect
import tokenize
from pathlib import Path

def tokens(path: Path) -> tuple[list[tokenize.TokenInfo], defaultdict]:
    with open(path) as fd:
        tokens = list(tokenize.tokenize(fd.readline))
    token_table = defaultdict(list)  # mapping line numbers to token numbers
    for index, token in enumerate(tokens):
        token_table[token.start[0]].append(index)
    return tokens, token_table


def endlineno(lineno: int, filepath: Path) -> int | None:
    tokens, tokens_by_line = tokens(filepath)
    first_token_index = tokens_by_line[lineno][0]
    blockfinder = inspect.BlockFinder()
    with suppress(inspect.EndOfBlock, tokenize.IndentationError):
        for token in tokens[first_token_index:]:
            blockfinder.tokeneater(*token)
    return blockfinder.last
```

**Comment by sondrelg** [comment]
Thanks @vect-tmazzucotelli, that's very helpful 👏 

I personally won't use this in a Python 3.7 project, so don't think I'll be able to prioritise this myself, but for anyone who would, PRs are welcome 🙂
