### ISSUE TITLE
ImportError due to circular import when running flake8 with this extension installed

### ISSUE THREAD

**Issue by nyuszika7h** [snok/flake8-type-checking#69]
I installed this extension because it says it can help avoid circular imports due to type annotations, but when running flake8 on a file with circular imports with this extension installed, it results in a traceback:

```
ImportError: cannot import name 'VideoTrack' from partially initialized module 'objects' (most likely due to a circular import) (objects/__init__.py)
```

I'm not sure if this is feasible to fix, it's not too hard to just manually fix these by putting them in `if TYPE_CHECKING` blocks, but I thought I'd report it.

I can't really share full details as this is from a private project, but I can try to make a minimal working example if necessary.

**Comment by sondrelg** [comment]
That's surprising. I was under the impression that flake8 performed static analysis of an individual file's code only. A minimal working example would be great 👍

**Comment by sondrelg** [comment]
I'm going to close this issue for now, but feel free to provide an mwe and I'll reopen 👍
