### ISSUE TITLE
2.0.1 causing other plugin to miss errors

### ISSUE THREAD

**Issue by jonyscathe** [snok/flake8-type-checking#90]
Hi,

Since 2.0.1 errors from flake8-unused-arguments have stopped being raised.
No issues with 2.0.0

**Comment by sondrelg** [comment]
Thanks for letting me know @jonyscathe. Would you be able to provide an mvp to reproduce the issue?

I think I know what's going on, but would be great to have a reproducible example.

**Comment by sondrelg** [comment]
I wonder if switching from `ast.NodeTransformer` to `ast.NodeVisitor` [here](https://github.com/snok/flake8-type-checking/blob/main/flake8_type_checking/checker.py#L290) might solve this issue, but would be great to get a second take

**Comment by sondrelg** [comment]
Would you mind testing whether #91 solves the issue @jonyscathe? 

If you're using poetry, you can install using `poetry add --dev git+https://github.com/snok/flake8-type-checking.git#main`

**Comment by jonyscathe** [comment]
Hi,
I am so sorry. I did mean to provide an mvp, but then got distracted with other things.
I can confirm that #91 does solve the issue. Everything appears to be fine if I pip install the @visitor branch.

**Comment by sondrelg** [comment]
Sweet, no worries :+1: I'll release the fix now. Thanks for reporting the issue!
